name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_PAGES: 1
  CF_PAGES_NAME: autoboop
  NODE_ENV: production
  VITE_API_BASE_URL: ${{ secrets.AUTOBOOP_API_URL }}
  VITE_FRONTEND_URL: ${{ secrets.AUTOBOOP_BASE_URL }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - name: Deploy cloudflare pages
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run deploy

  deploy-workers:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: workers

    steps:
      - uses: actions/checkout@v3
      - name: Deploy cloudflare workers
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run deploy